CREATE TABLE EGABAY_ADMINS (
    ADMIN_ID      VARCHAR(36)  NOT NULL PRIMARY KEY,
    USERNAME      VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME     VARCHAR(255) NOT NULL,
    ROLE          VARCHAR(50)  NOT NULL
);
